## Import Libraries

In [1]:
import pandas as pd

## Data Collection

In [4]:
movie_data = pd.read_csv("movie.csv")
movie_data

      userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

## Data Understanding

In [9]:
movie_data.shape

(8992, 3)

In [13]:
movie_data.isna().sum()

userId    0
movie     0
rating    0
dtype: int64

In [14]:
movie_data.dtypes

userId      int64
movie      object
rating    float64
dtype: object

In [11]:
movie_data["userId"].nunique()

4081

In [8]:
movie_data["userId"].value_counts()

userId
903     10
1931    10
5881    10
1638     9
156      9
        ..
6911     1
6851     1
6909     1
6850     1
6300     1
Name: count, Length: 4081, dtype: int64

## Data Preparation

In [20]:
piv_table= pd.pivot_table(data =movie_data ,values="rating",  index="movie", columns="userId",fill_value=0)
piv_table

userId,1,2,3,4,5,6,7,8,10,11,...,7105,7107,7108,7110,7113,7115,7116,7117,7119,7120
movie,,,,,,,,,,,,,,,,,,,,,
Father of the Bride Part II (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,3.5,0.0,0.0,0.0
GoldenEye (1995),0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,2.5,...,2.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0
Grumpier Old Men (1995),0.0,4.0,0.0,0.0,0.0,3.0,3.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0
Heat (1995),0.0,0.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,5.0,0.0,0.0
Jumanji (1995),3.5,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0
Sabrina (1995),0.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,4.0
Sudden Death (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Tom and Huck (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Toy Story (1995),0.0,0.0,4.0,0.0,0.0,5.0,0.0,4.0,4.0,4.5,...,0.0,4.0,0.0,4.0,0.0,0.0,4.0,4.0,5.0,4.5
Waiting to Exhale (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
piv_table.columns = movie_data["userId"].unique()
piv_table

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
movie,,,,,,,,,,,,,,,,,,,,,
Father of the Bride Part II (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,3.5,0.0,0.0,0.0
GoldenEye (1995),0.0,0.0,0.0,4.0,0.0,0.0,0.0,4.0,0.0,2.5,...,2.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,0.0
Grumpier Old Men (1995),0.0,4.0,0.0,0.0,0.0,3.0,3.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0
Heat (1995),0.0,0.0,0.0,3.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,5.0,0.0,0.0
Jumanji (1995),3.5,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,4.0,0.0,0.0,0.0,0.0,0.0,4.0
Sabrina (1995),0.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,4.0
Sudden Death (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Tom and Huck (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Toy Story (1995),0.0,0.0,4.0,0.0,0.0,5.0,0.0,4.0,4.0,4.5,...,0.0,4.0,0.0,4.0,0.0,0.0,4.0,4.0,5.0,4.5
Waiting to Exhale (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
piv_table.corr().round(2)

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,1.00,-0.11,-0.11,-0.16,1.00,-0.21,-0.17,-0.27,-0.11,-0.16,...,-0.11,-0.11,1.00,0.67,-0.17,-0.11,-0.17,-0.35,-0.11,0.48
6,-0.11,1.00,-0.11,-0.16,-0.11,0.28,0.67,0.56,-0.11,-0.16,...,-0.11,-0.11,-0.11,-0.17,-0.17,-0.11,-0.17,0.35,-0.11,-0.22
8,-0.11,-0.11,1.00,-0.16,-0.11,0.60,-0.17,0.40,1.00,0.86,...,-0.11,1.00,-0.11,0.67,-0.17,-0.11,0.72,0.35,1.00,0.57
10,-0.16,-0.16,-0.16,1.00,-0.16,-0.31,-0.25,0.48,-0.16,0.24,...,0.78,-0.16,-0.16,-0.25,0.99,-0.16,-0.25,0.48,-0.16,-0.32
11,1.00,-0.11,-0.11,-0.16,1.00,-0.21,-0.17,-0.27,-0.11,-0.16,...,-0.11,-0.11,1.00,0.67,-0.17,-0.11,-0.17,-0.35,-0.11,0.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,-0.11,-0.11,-0.11,-0.16,-0.11,-0.21,-0.17,-0.27,-0.11,-0.16,...,-0.11,-0.11,-0.11,-0.17,-0.17,1.00,0.61,-0.35,-0.11,-0.22
7070,-0.17,-0.17,0.72,-0.25,-0.17,0.33,-0.25,0.13,0.72,0.58,...,-0.17,0.72,-0.17,0.42,-0.25,0.61,1.00,0.04,0.72,0.30
7080,-0.35,0.35,0.35,0.48,-0.35,0.54,0.40,0.81,0.35,0.41,...,0.18,0.35,-0.35,0.00,0.53,-0.35,0.04,1.00,0.35,0.14
7087,-0.11,-0.11,1.00,-0.16,-0.11,0.60,-0.17,0.40,1.00,0.86,...,-0.11,1.00,-0.11,0.67,-0.17,-0.11,0.72,0.35,1.00,0.57
7105,0.48,-0.22,0.57,-0.32,0.48,0.67,0.20,-0.05,0.57,0.41,...,-0.22,0.57,0.48,0.78,-0.33,-0.22,0.30,0.14,0.57,1.00

## Building UBCF using Euclidean distance

In [28]:
from sklearn.metrics import pairwise_distances

In [30]:
euclidean_piv_table= pd.pivot_table(data =movie_data ,values="rating",  index="userId", columns="movie",fill_value=0)
euclidean_piv_table.columns = movie_data["movie"].unique()
euclidean_piv_table.index = movie_data["userId"].unique()
euclidean_piv_table

,Toy Story (1995),Jumanji (1995),Grumpier Old Men (1995),Waiting to Exhale (1995),Father of the Bride Part II (1995),Heat (1995),Sabrina (1995),Tom and Huck (1995),Sudden Death (1995),GoldenEye (1995)
3,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
10,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
7044,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7070,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
7080,0.0,3.0,4.0,5.0,0.0,3.0,1.0,0.0,4.0,0.0
7087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
7105,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,4.5,0.0

In [33]:
euclidean_correlation = pd.DataFrame(pairwise_distances(X = euclidean_piv_table,metric='euclidean'))
euclidean_correlation.columns = movie_data["userId"].unique()
euclidean_correlation.index = movie_data["userId"].unique()
euclidean_correlation

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,0.000000,5.315073,5.315073,6.103278,0.500000,8.440972,5.500000,8.845903,5.315073,6.224950,...,4.031129,5.315073,1.500000,4.031129,5.500000,5.315073,6.363961,9.394147,6.103278,6.041523
6,5.315073,0.000000,5.656854,6.403124,5.000000,7.141428,3.162278,6.480741,5.656854,6.519202,...,4.472136,5.656854,4.472136,6.928203,5.830952,5.656854,6.652067,7.745967,6.403124,8.261356
8,5.315073,5.656854,0.000000,6.403124,5.000000,5.916080,5.830952,7.071068,0.000000,2.549510,...,4.472136,0.000000,4.472136,4.000000,5.830952,5.656854,3.500000,7.745967,1.000000,5.678908
10,6.103278,6.403124,6.403124,0.000000,5.830952,9.165151,6.557439,6.403124,6.403124,5.612486,...,3.605551,6.403124,5.385165,7.549834,1.000000,6.403124,7.297260,6.855655,7.071068,8.789198
11,0.500000,5.000000,5.000000,5.830952,0.000000,8.246211,5.196152,8.660254,5.000000,5.958188,...,3.605551,5.000000,1.000000,4.123106,5.196152,5.000000,6.103278,9.219544,5.830952,6.103278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,5.315073,5.656854,5.656854,6.403124,5.000000,8.660254,5.830952,9.055385,5.656854,6.519202,...,4.472136,5.656854,4.472136,6.928203,5.830952,0.000000,4.031129,9.591663,6.403124,8.261356
7070,6.363961,6.652067,3.500000,7.297260,6.103278,6.873864,6.800735,7.889867,3.500000,4.330127,...,5.678908,3.500000,5.678908,5.315073,6.800735,4.031129,0.000000,8.500000,3.640055,6.670832
7080,9.394147,7.745967,7.745967,6.855655,9.219544,6.403124,7.211103,4.000000,7.745967,7.176350,...,8.246211,7.745967,8.944272,8.717798,6.782330,9.591663,8.500000,0.000000,7.810250,8.261356
7087,6.103278,6.403124,1.000000,7.071068,5.830952,5.830952,6.557439,7.141428,1.000000,2.549510,...,5.385165,1.000000,5.385165,4.123106,6.557439,6.403124,3.640055,7.810250,0.000000,5.678908
7105,6.041523,8.261356,5.678908,8.789198,6.103278,5.123475,6.800735,9.069179,5.678908,6.184658,...,7.500000,5.678908,6.344289,4.031129,8.381527,8.261356,6.670832,8.261356,5.678908,0.000000

## Building UBCF using Cosine Similarity

In [35]:
cosine_correlation = pd.DataFrame(1 - pairwise_distances(X = euclidean_piv_table,metric='cosine'))
cosine_correlation.columns = movie_data["userId"].unique()
cosine_correlation.index = movie_data["userId"].unique()
cosine_correlation

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.553372
6,0.000000,1.000000,0.000000,0.000000,0.000000,0.390567,0.707107,0.615457,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.458831,0.000000,0.000000
8,0.000000,0.000000,1.000000,0.000000,0.000000,0.650945,0.000000,0.492366,1.000000,0.874157,...,0.000000,1.000000,0.000000,0.707107,0.000000,0.000000,0.752577,0.458831,1.000000,0.622543
10,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.615457,0.000000,0.388514,...,0.800000,0.000000,0.000000,0.000000,0.989949,0.000000,0.000000,0.619422,0.000000,0.000000
11,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.553372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.658505,0.000000,0.000000,0.000000
7070,0.000000,0.000000,0.752577,0.000000,0.000000,0.489886,0.000000,0.370543,0.752577,0.657870,...,0.000000,0.752577,0.000000,0.532152,0.000000,0.658505,1.000000,0.345306,0.752577,0.468511
7080,0.000000,0.458831,0.458831,0.619422,0.000000,0.701884,0.567775,0.889532,0.458831,0.568212,...,0.344124,0.458831,0.000000,0.324443,0.648886,0.000000,0.345306,1.000000,0.458831,0.476071
7087,0.000000,0.000000,1.000000,0.000000,0.000000,0.650945,0.000000,0.492366,1.000000,0.874157,...,0.000000,1.000000,0.000000,0.707107,0.000000,0.000000,0.752577,0.458831,1.000000,0.622543
7105,0.553372,0.000000,0.622543,0.000000,0.553372,0.765455,0.391293,0.306519,0.622543,0.544201,...,0.000000,0.622543,0.553372,0.831497,0.000000,0.000000,0.468511,0.476071,0.622543,1.000000